/* Generated By:JavaCC: Do not edit this line. Trabalho01Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Trabalho01Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 6;
  /** RegularExpression Id. */
  int COMENTARIO_LINHA = 7;
  /** RegularExpression Id. */
  int COMENTARIO_BLOCO = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int PARENTESE_A = 10;
  /** RegularExpression Id. */
  int PARENTESE_F = 11;
  /** RegularExpression Id. */
  int CHAVE_A = 12;
  /** RegularExpression Id. */
  int CHAVE_F = 13;
  /** RegularExpression Id. */
  int LITERAL = 14;
  /** RegularExpression Id. */
  int OPERADOR_RELACIONAL = 15;
  /** RegularExpression Id. */
  int NUMBER = 16;
  /** RegularExpression Id. */
  int LETTER = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\";\"",
    "<COMENTARIO_LINHA>",
    "<COMENTARIO_BLOCO>",
    "\"sepa\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "<LITERAL>",
    "<OPERADOR_RELACIONAL>",
    "<NUMBER>",
    "<LETTER>",
  };

}
