/* Trabalho01TokenManager.java */
/* Generated By:JavaCC: Do not edit this line. Trabalho01TokenManager.java */
import java.io.FileInputStream;
import java.io.File;
import java.io.IOException;

/** Token Manager. */
@SuppressWarnings ("unused")
public class Trabalho01TokenManager implements Trabalho01Constants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0){
      debugStream.println("   No more string literal token matches are possible.");
   switch (pos)
   {
      case 0:
         if ((active0 & 0x8000L) != 0L)
         {
            jjmatchedKind = 33;
            return 4;
         }
         if ((active0 & 0x7614000L) != 0L)
         {
            jjmatchedKind = 33;
            return 80;
         }
         if ((active0 & 0x100000000L) != 0L)
            return 25;
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 33;
            return 47;
         }
         if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 33;
            return 21;
         }
         return -1;
      case 1:
         if ((active0 & 0xf61c000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 1;
            return 81;
         }
         if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 1;
            return 20;
         }
         return -1;
      case 2:
         if ((active0 & 0xfe1c000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 2;
            return 81;
         }
         return -1;
      case 3:
         if ((active0 & 0xf81c000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 3;
            }
            return 81;
         }
         if ((active0 & 0x600000L) != 0L)
            return 81;
         return -1;
      case 4:
         if ((active0 & 0xfc18000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 4;
            return 81;
         }
         if ((active0 & 0x4000L) != 0L)
            return 81;
         return -1;
      case 5:
         if ((active0 & 0x6400000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 5;
            return 81;
         }
         if ((active0 & 0x9818000L) != 0L)
            return 81;
         return -1;
      case 6:
         if ((active0 & 0x2400000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 6;
            return 81;
         }
         if ((active0 & 0x4000000L) != 0L)
            return 81;
         return -1;
      case 7:
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 7;
            return 81;
         }
         if ((active0 & 0x400000L) != 0L)
            return 81;
         return -1;
      case 8:
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 8;
            return 81;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   debugStream.println("   No more string literal token matches are possible.");
   debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 13:
         jjmatchedKind = 4;
         return jjMoveStringLiteralDfa1_0(0x20L);
      case 40:
         return jjStopAtPos(0, 28);
      case 41:
         return jjStopAtPos(0, 29);
      case 44:
         return jjStopAtPos(0, 37);
      case 59:
         return jjStopAtPos(0, 36);
      case 61:
         return jjStartNfaWithStates_0(0, 32, 25);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x4000000L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x2000000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x8000000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x8000L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x1000000L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x10000L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x604000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x800000L);
      case 123:
         return jjStopAtPos(0, 30);
      case 125:
         return jjStopAtPos(0, 31);
      default :
      debugStream.println("   No string literal matches possible.");
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0){
   if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
      debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   debugStream.println("   Possible string literal matches : { "
 +
         jjKindsForBitVector(0, active0)  + " } ");
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
         debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
      return 1;
   }
   debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   switch(curChar)
   {
      case 10:
         if ((active0 & 0x20L) != 0L)
            return jjStopAtPos(1, 5);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x2610000L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000L);
      default :
      debugStream.println("   No string literal matches possible.");
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
      debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   debugStream.println("   Possible string literal matches : { "
 +
         jjKindsForBitVector(0, active0)  + " } ");
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
         debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
      return 2;
   }
   debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x608000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000L);
      default :
      debugStream.println("   No string literal matches possible.");
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
      debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   debugStream.println("   Possible string literal matches : { "
 +
         jjKindsForBitVector(0, active0)  + " } ");
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
         debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
      return 3;
   }
   debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x200000L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x400000L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L);
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000L);
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000L);
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x1008000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
      default :
      debugStream.println("   No string literal matches possible.");
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
      debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   debugStream.println("   Possible string literal matches : { "
 +
         jjKindsForBitVector(0, active0)  + " } ");
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
         debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
      return 4;
   }
   debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0xc000000L);
      case 101:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(4, 14, 81);
         break;
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L);
      case 112:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000L);
      case 113:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x18000L);
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000L);
      default :
      debugStream.println("   No string literal matches possible.");
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
      debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   debugStream.println("   Possible string literal matches : { "
 +
         jjKindsForBitVector(0, active0)  + " } ");
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
         debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
      return 5;
   }
   debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(5, 24, 81);
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000L);
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000L);
      case 110:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(5, 16, 81);
         return jjMoveStringLiteralDfa6_0(active0, 0x400000L);
      case 111:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(5, 23, 81);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(5, 27, 81);
         break;
      case 116:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(5, 15, 81);
         break;
      default :
      debugStream.println("   No string literal matches possible.");
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
      debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   debugStream.println("   Possible string literal matches : { "
 +
         jjKindsForBitVector(0, active0)  + " } ");
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
         debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
      return 6;
   }
   debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000L);
      case 105:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(6, 26, 81);
         break;
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000L);
      default :
      debugStream.println("   No string literal matches possible.");
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
      debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   debugStream.println("   Possible string literal matches : { "
 +
         jjKindsForBitVector(0, active0)  + " } ");
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
         debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
      return 7;
   }
   debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000L);
      case 111:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(7, 22, 81);
         break;
      default :
      debugStream.println("   No string literal matches possible.");
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
      debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   debugStream.println("   Possible string literal matches : { "
 +
         jjKindsForBitVector(0, active0)  + " } ");
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
         debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
      return 8;
   }
   debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   switch(curChar)
   {
      case 104:
         return jjMoveStringLiteralDfa9_0(active0, 0x2000000L);
      default :
      debugStream.println("   No string literal matches possible.");
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
      debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   debugStream.println("   Possible string literal matches : { "
 +
         jjKindsForBitVector(0, active0)  + " } ");
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
         debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
      return 9;
   }
   debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(9, 25, 81);
         break;
      default :
      debugStream.println("   No string literal matches possible.");
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   debugStream.println("   No more string literal token matches are possible.");
   debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 80;
   int i = 1;
   jjstateSet[0] = startState;
      debugStream.println("   Starting NFA to match one of : " + jjKindsForStateVector(curLexState, jjstateSet, 0, 1));
      debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 80:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(0, 4); }
                  }
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 70;
                  else if (curChar == 43)
                     jjstateSet[jjnewStateCnt++] = 61;
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(5, 10); }
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(11, 16); }
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(0, 4); }
                  }
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 70;
                  else if (curChar == 43)
                     jjstateSet[jjnewStateCnt++] = 61;
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(5, 10); }
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(11, 16); }
                  break;
               case 81:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(0, 4); }
                  }
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 70;
                  else if (curChar == 43)
                     jjstateSet[jjnewStateCnt++] = 61;
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(5, 10); }
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(11, 16); }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 35)
                        kind = 35;
                     { jjCheckNAddStates(17, 19); }
                  }
                  else if ((0xac0000000000L & l) != 0L)
                  {
                     if (kind > 20)
                        kind = 20;
                  }
                  else if ((0x5000000000000000L & l) != 0L)
                  {
                     if (kind > 34)
                        kind = 34;
                  }
                  else if (curChar == 33)
                     { jjCheckNAdd(25); }
                  else if (curChar == 61)
                     { jjCheckNAdd(25); }
                  else if (curChar == 34)
                     { jjCheckNAddTwoStates(1, 2); }
                  if (curChar == 47)
                     { jjAddStates(20, 21); }
                  else if (curChar == 62)
                     { jjCheckNAdd(25); }
                  else if (curChar == 60)
                     { jjCheckNAdd(25); }
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(0, 4); }
                  }
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 70;
                  else if (curChar == 43)
                     jjstateSet[jjnewStateCnt++] = 61;
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(5, 10); }
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(11, 16); }
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(0, 4); }
                  }
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 70;
                  else if (curChar == 43)
                     jjstateSet[jjnewStateCnt++] = 61;
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(5, 10); }
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(11, 16); }
                  break;
               case 47:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(0, 4); }
                  }
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 70;
                  else if (curChar == 43)
                     jjstateSet[jjnewStateCnt++] = 61;
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(5, 10); }
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(11, 16); }
                  break;
               case 1:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(1, 2); }
                  break;
               case 2:
                  if (curChar == 34 && kind > 8)
                     kind = 8;
                  break;
               case 23:
                  if ((0xac0000000000L & l) != 0L && kind > 20)
                     kind = 20;
                  break;
               case 24:
                  if ((0x5000000000000000L & l) != 0L && kind > 34)
                     kind = 34;
                  break;
               case 25:
                  if (curChar == 61 && kind > 34)
                     kind = 34;
                  break;
               case 26:
                  if (curChar == 60)
                     { jjCheckNAdd(25); }
                  break;
               case 27:
                  if (curChar == 62)
                     { jjCheckNAdd(25); }
                  break;
               case 28:
                  if (curChar == 61)
                     { jjCheckNAdd(25); }
                  break;
               case 29:
                  if (curChar == 33)
                     { jjCheckNAdd(25); }
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 35)
                     kind = 35;
                  { jjCheckNAddStates(17, 19); }
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 35)
                     kind = 35;
                  { jjCheckNAdd(31); }
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(32, 33); }
                  break;
               case 33:
                  if (curChar == 44)
                     { jjCheckNAdd(34); }
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 35)
                     kind = 35;
                  { jjCheckNAdd(34); }
                  break;
               case 35:
                  if (curChar == 47)
                     { jjAddStates(20, 21); }
                  break;
               case 36:
                  if (curChar != 47)
                     break;
                  if (kind > 6)
                     kind = 6;
                  { jjCheckNAdd(37); }
                  break;
               case 37:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  { jjCheckNAdd(37); }
                  break;
               case 38:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(39, 40); }
                  break;
               case 39:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(39, 40); }
                  break;
               case 40:
                  if (curChar == 42)
                     { jjCheckNAddStates(22, 24); }
                  break;
               case 41:
                  if ((0xffff7bffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(42, 40); }
                  break;
               case 42:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(42, 40); }
                  break;
               case 43:
                  if (curChar == 47 && kind > 7)
                     kind = 7;
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  { jjCheckNAddStates(0, 4); }
                  break;
               case 55:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(55, 56); }
                  break;
               case 56:
                  if (curChar == 44)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  { jjCheckNAddStates(25, 27); }
                  break;
               case 58:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  { jjCheckNAddStates(28, 33); }
                  break;
               case 61:
                  if (curChar == 43 && kind > 38)
                     kind = 38;
                  break;
               case 62:
                  if (curChar == 43)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(5, 10); }
                  break;
               case 64:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(64, 65); }
                  break;
               case 65:
                  if (curChar == 44)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(34, 37); }
                  break;
               case 67:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(38, 44); }
                  break;
               case 70:
                  if (curChar == 45 && kind > 38)
                     kind = 38;
                  break;
               case 71:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 72:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(11, 16); }
                  break;
               case 73:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(73, 74); }
                  break;
               case 74:
                  if (curChar == 44)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 75:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(45, 48); }
                  break;
               case 76:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(49, 55); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 80:
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(56, 59); }
                  }
                  else if (curChar == 95)
                     { jjCheckNAddStates(60, 63); }
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(64, 68); }
                  else if (curChar == 95)
                     { jjCheckNAddStates(69, 72); }
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(73, 77); }
                  else if (curChar == 95)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(78, 80); }
                  }
                  break;
               case 21:
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(56, 59); }
                  }
                  else if (curChar == 95)
                     { jjCheckNAddStates(60, 63); }
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(64, 68); }
                  else if (curChar == 95)
                     { jjCheckNAddStates(69, 72); }
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(73, 77); }
                  else if (curChar == 95)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(78, 80); }
                  }
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 81:
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(56, 59); }
                  }
                  else if (curChar == 95)
                     { jjCheckNAddStates(60, 63); }
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(64, 68); }
                  else if (curChar == 95)
                     { jjCheckNAddStates(69, 72); }
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(73, 77); }
                  else if (curChar == 95)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(78, 80); }
                  }
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(60, 63); }
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(69, 72); }
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(78, 80); }
                  }
                  break;
               case 0:
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(81, 91); }
                  }
                  else if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 10;
                  if (curChar == 102)
                     { jjAddStates(92, 93); }
                  else if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 21;
                  else if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 17;
                  else if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 20:
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(56, 59); }
                  }
                  else if (curChar == 95)
                     { jjCheckNAddStates(60, 63); }
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(64, 68); }
                  else if (curChar == 95)
                     { jjCheckNAddStates(69, 72); }
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(73, 77); }
                  else if (curChar == 95)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(78, 80); }
                  }
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(60, 63); }
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(69, 72); }
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(78, 80); }
                  }
                  if (curChar == 117)
                     { jjCheckNAdd(19); }
                  break;
               case 4:
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(56, 59); }
                  }
                  else if (curChar == 95)
                     { jjCheckNAddStates(60, 63); }
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(64, 68); }
                  else if (curChar == 95)
                     { jjCheckNAddStates(69, 72); }
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(73, 77); }
                  else if (curChar == 95)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(78, 80); }
                  }
                  if (curChar == 110)
                     { jjCheckNAdd(3); }
                  break;
               case 47:
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(56, 59); }
                  }
                  else if (curChar == 95)
                     { jjCheckNAddStates(60, 63); }
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(64, 68); }
                  else if (curChar == 95)
                     { jjCheckNAddStates(69, 72); }
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(73, 77); }
                  else if (curChar == 95)
                  {
                     if (kind > 33)
                        kind = 33;
                     { jjCheckNAddStates(78, 80); }
                  }
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 49;
                  else if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 1:
                  { jjAddStates(94, 95); }
                  break;
               case 3:
                  if (curChar == 116 && kind > 9)
                     kind = 9;
                  break;
               case 5:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 103 && kind > 9)
                     kind = 9;
                  break;
               case 7:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 10:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 110 && kind > 9)
                     kind = 9;
                  break;
               case 13:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 14:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if (curChar == 101 && kind > 17)
                     kind = 17;
                  break;
               case 22:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 37:
                  if (kind > 6)
                     kind = 6;
                  jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  { jjCheckNAddTwoStates(39, 40); }
                  break;
               case 41:
               case 42:
                  { jjCheckNAddTwoStates(42, 40); }
                  break;
               case 44:
                  if (curChar == 102)
                     { jjAddStates(92, 93); }
                  break;
               case 45:
                  if (curChar == 97)
                     { jjCheckNAdd(3); }
                  break;
               case 46:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 48:
                  if (curChar == 115)
                     { jjCheckNAdd(19); }
                  break;
               case 49:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 50:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 51:
                  if ((0x7fffffe00000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  { jjCheckNAddStates(81, 91); }
                  break;
               case 52:
                  if (curChar != 95)
                     break;
                  if (kind > 33)
                     kind = 33;
                  { jjCheckNAddStates(78, 80); }
                  break;
               case 53:
                  if ((0x7fffffe00000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  { jjCheckNAddStates(78, 80); }
                  break;
               case 59:
                  if (curChar == 95)
                     { jjCheckNAddStates(69, 72); }
                  break;
               case 60:
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(69, 72); }
                  break;
               case 68:
                  if (curChar == 95)
                     { jjCheckNAddStates(60, 63); }
                  break;
               case 69:
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(60, 63); }
                  break;
               case 77:
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(73, 77); }
                  break;
               case 78:
                  if ((0x7fffffe00000000L & l) != 0L)
                     { jjCheckNAddStates(64, 68); }
                  break;
               case 79:
                  if ((0x7fffffe00000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  { jjCheckNAddStates(56, 59); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(94, 95); }
                  break;
               case 37:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddTwoStates(39, 40); }
                  break;
               case 41:
               case 42:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddTwoStates(42, 40); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
         debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
      if ((i = jjnewStateCnt) == (startsAt = 80 - (jjnewStateCnt = startsAt)))
         return curPos;
      debugStream.println("   Possible kinds of longer matches : " + jjKindsForStateVector(curLexState, jjstateSet, startsAt, i));
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
      debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, "\163\141\154\166\145", "\151\155\160\157\162\164", 
"\162\145\164\165\162\156", null, null, null, null, "\163\145\160\141", 
"\163\145\160\141\161\156\141\157", "\164\162\141\155\160\157", "\155\157\143\157\164\141", 
"\144\145\163\145\155\142\165\143\150\141", "\143\150\145\147\141\141\151", "\146\165\156\143\141\157", "\50", "\51", 
"\173", "\175", "\75", null, null, null, "\73", "\54", null, null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   53, 52, 55, 56, 54, 60, 59, 64, 65, 62, 63, 69, 68, 73, 74, 71, 
   72, 31, 32, 33, 36, 38, 41, 40, 43, 53, 52, 58, 53, 52, 55, 56, 
   54, 58, 60, 59, 62, 67, 60, 59, 64, 65, 62, 63, 67, 69, 68, 71, 
   76, 69, 68, 73, 74, 71, 72, 76, 53, 52, 54, 79, 69, 68, 71, 72, 
   60, 59, 62, 63, 78, 60, 59, 62, 63, 69, 68, 71, 72, 77, 53, 52, 
   54, 52, 59, 62, 68, 71, 72, 77, 63, 78, 54, 79, 47, 50, 1, 2, 
};

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      debugStream.println("Returning the <EOF> token.\n");
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100000600L & (1L << curChar)) != 0L)
   {
      debugStream.println("Skipping character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ")");
         curChar = input_stream.BeginToken();
   }
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
      debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
      {
         debugStream.println("   Putting back " + (curPos - jjmatchedPos - 1) + " characters into the input stream.");
         input_stream.backup(curPos - jjmatchedPos - 1);
      }
    debugStream.println("****** FOUND A " + tokenImage[jjmatchedKind] + " MATCH (" + TokenMgrError.addEscapes(new String(input_stream.GetSuffix(jjmatchedPos + 1))) + ") ******\n");
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

protected static final int[][][] statesForState = {
 {
   { 0, 5, 11, 18, 22, 23, 24, 26, 27, 28, 29, 30, 35, 44, 51, },
   { 1 },
   { 2 },
   { 3 },
   { 4, 52, 59, 62, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 0, 5, 11, 18, 22, 23, 24, 26, 27, 28, 29, 30, 35, 44, 51, },
   { 6 },
   { 7 },
   { 8 },
   { 9 },
   { 10 },
   { 0, 5, 11, 18, 22, 23, 24, 26, 27, 28, 29, 30, 35, 44, 51, },
   { 12 },
   { 13 },
   { 14 },
   { 15 },
   { 16 },
   { 17 },
   { 0, 5, 11, 18, 22, 23, 24, 26, 27, 28, 29, 30, 35, 44, 51, },
   { 19 },
   { 20, 53, 52, 60, 59, 62, 69, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 21, 52, 59, 62, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 0, 5, 11, 18, 22, 23, 24, 26, 27, 28, 29, 30, 35, 44, 51, },
   { 0, 5, 11, 18, 22, 23, 24, 26, 27, 28, 29, 30, 35, 44, 51, },
   { 0, 5, 11, 18, 22, 23, 24, 26, 27, 28, 29, 30, 35, 44, 51, },
   { 25 },
   { 0, 5, 11, 18, 22, 23, 24, 26, 27, 28, 29, 30, 35, 44, 51, },
   { 0, 5, 11, 18, 22, 23, 24, 26, 27, 28, 29, 30, 35, 44, 51, },
   { 0, 5, 11, 18, 22, 23, 24, 26, 27, 28, 29, 30, 35, 44, 51, },
   { 0, 5, 11, 18, 22, 23, 24, 26, 27, 28, 29, 30, 35, 44, 51, },
   { 0, 5, 11, 18, 22, 23, 24, 26, 27, 28, 29, 30, 35, 44, 51, },
   { 31 },
   { 32 },
   { 33 },
   { 34 },
   { 0, 5, 11, 18, 22, 23, 24, 26, 27, 28, 29, 30, 35, 44, 51, },
   { 36 },
   { 37 },
   { 38 },
   { 39 },
   { 40 },
   { 41 },
   { 42 },
   { 43 },
   { 0, 5, 11, 18, 22, 23, 24, 26, 27, 28, 29, 30, 35, 44, 51, },
   { 45 },
   { 46 },
   { 47, 50, 52, 59, 62, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 48 },
   { 49 },
   { 47, 50, 52, 59, 62, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 0, 5, 11, 18, 22, 23, 24, 26, 27, 28, 29, 30, 35, 44, 51, },
   { 20, 53, 52, 60, 59, 62, 69, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 20, 53, 52, 60, 59, 62, 69, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 20, 53, 52, 60, 59, 62, 69, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 55 },
   { 56 },
   { 57 },
   { 58 },
   { 20, 53, 52, 60, 59, 62, 69, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 20, 53, 52, 60, 59, 62, 69, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 61 },
   { 20, 53, 52, 60, 59, 62, 69, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 20, 53, 52, 60, 59, 62, 69, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 64 },
   { 65 },
   { 66 },
   { 67 },
   { 20, 53, 52, 60, 59, 62, 69, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 20, 53, 52, 60, 59, 62, 69, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 70 },
   { 20, 53, 52, 60, 59, 62, 69, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 20, 53, 52, 60, 59, 62, 69, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 73 },
   { 74 },
   { 75 },
   { 76 },
   { 20, 53, 52, 60, 59, 62, 69, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 20, 53, 52, 60, 59, 62, 69, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 20, 53, 52, 60, 59, 62, 69, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 52, 59, 62, 68, 71, 72, 77, 63, 78, 54, 79, },
   { 53, 52, 60, 59, 62, 69, 68, 71, 72, 77, 63, 78, 54, 79, },
},

};
protected static final int[][] kindForState = {
{ 
  8, 
  8, 
  8, 
  9, 
  9, 
  9, 
  9, 
  9, 
  9, 
  9, 
  9, 
  9, 
  9, 
  9, 
  9, 
  9, 
  9, 
  9, 
  9, 
  17, 
  17, 
  17, 
  17, 
  20, 
  34, 
  34, 
  34, 
  34, 
  34, 
  34, 
  35, 
  35, 
  35, 
  35, 
  35, 
  6, 
  6, 
  6, 
  7, 
  7, 
  7, 
  7, 
  7, 
  7, 
  9, 
  9, 
  9, 
  9, 
  17, 
  17, 
  17, 
  33, 
  33, 
  33, 
  33, 
  33, 
  33, 
  33, 
  33, 
  38, 
  38, 
  38, 
  38, 
  38, 
  38, 
  38, 
  38, 
  38, 
  38, 
  38, 
  38, 
  38, 
  38, 
  38, 
  38, 
  38, 
  38, 
  38, 
  38, 
  33, }
};
  int kindCnt = 0;
  protected final String jjKindsForBitVector(int i, long vec)
  {
    String retVal = "";
    if (i == 0)
       kindCnt = 0;
    for (int j = 0; j < 64; j++)
    {
       if ((vec & (1L << j)) != 0L)
       {
          if (kindCnt++ > 0)
             retVal += ", ";
          if (kindCnt % 5 == 0)
             retVal += "\n     ";
          retVal += tokenImage[i * 64 + j];
       }
    }
    return retVal;
  }


  protected final String jjKindsForStateVector(int lexState, int[] vec, int start, int end)
  {
    boolean[] kindDone = new boolean[41];
    String retVal = "";
    int cnt = 0;
    for (int i = start; i < end; i++)
    {
     if (vec[i] == -1)
       continue;
     int[] stateSet = statesForState[curLexState][vec[i]];
     for (int j = 0; j < stateSet.length; j++)
     {
       int state = stateSet[j];
       if (!kindDone[kindForState[lexState][state]])
       {
          kindDone[kindForState[lexState][state]] = true;
          if (cnt++ > 0)
             retVal += ", ";
          if (cnt % 5 == 0)
             retVal += "\n     ";
          retVal += tokenImage[kindForState[lexState][state]];
       }
     }
    }
    if (cnt == 0)
       return "{  }";
    else
       return "{ " + retVal + " }";
  }


void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public Trabalho01TokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public Trabalho01TokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 80; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0x7ffff3c3c1L, 
};
static final long[] jjtoSkip = {
   0x3eL, 
};
static final long[] jjtoSpecial = {
   0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[80];
    private final int[] jjstateSet = new int[2 * 80];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
