/* Generated By:JavaCC: Do not edit this line. Trabalho01Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Trabalho01Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO_LINHA = 6;
  /** RegularExpression Id. */
  int COMENTARIO_BLOCO = 7;
  /** RegularExpression Id. */
  int TIPO = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int BYTE = 11;
  /** RegularExpression Id. */
  int SHORT = 12;
  /** RegularExpression Id. */
  int LONG = 13;
  /** RegularExpression Id. */
  int FLOAT = 14;
  /** RegularExpression Id. */
  int DOUBLE = 15;
  /** RegularExpression Id. */
  int CHAR = 16;
  /** RegularExpression Id. */
  int BOOLEAN = 17;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int ELSE = 20;
  /** RegularExpression Id. */
  int WHILE = 21;
  /** RegularExpression Id. */
  int FOR = 22;
  /** RegularExpression Id. */
  int INPUT = 23;
  /** RegularExpression Id. */
  int PRINT = 24;
  /** RegularExpression Id. */
  int FUNCAO = 25;
  /** RegularExpression Id. */
  int PARENTESE_A = 26;
  /** RegularExpression Id. */
  int PARENTESE_F = 27;
  /** RegularExpression Id. */
  int CHAVE_A = 28;
  /** RegularExpression Id. */
  int CHAVE_F = 29;
  /** RegularExpression Id. */
  int ATRIBUICAO = 30;
  /** RegularExpression Id. */
  int LITERAL = 31;
  /** RegularExpression Id. */
  int OPERADOR_RELACIONAL = 32;
  /** RegularExpression Id. */
  int VALUE = 33;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 34;
  /** RegularExpression Id. */
  int VIRGULA = 35;
  /** RegularExpression Id. */
  int INC_DEC = 36;
  /** RegularExpression Id. */
  int NUMBER = 37;
  /** RegularExpression Id. */
  int LETTER = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<COMENTARIO_LINHA>",
    "<COMENTARIO_BLOCO>",
    "<TIPO>",
    "\"int\"",
    "\"String\"",
    "\"byte\"",
    "\"short\"",
    "\"long\"",
    "\"float\"",
    "\"double\"",
    "\"char\"",
    "\"boolean\"",
    "<OPERADOR_ARITMETICO>",
    "\"sepa\"",
    "\"sepaqnao\"",
    "\"trampo\"",
    "\"mocota\"",
    "\"desembucha\"",
    "\"chegaai\"",
    "\"funcao\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "<LITERAL>",
    "<OPERADOR_RELACIONAL>",
    "<VALUE>",
    "\";\"",
    "\",\"",
    "<INC_DEC>",
    "<NUMBER>",
    "<LETTER>",
    "\"\\\"\"",
  };

}
